### PR TITLE
Improve patch task and treatment of shell meta-characters.

### PR DESCRIPTION
**Pull request by knu**
I've made some enhancements to help end users and recipe writers.

See the entries in History.txt for details.

This PR is a by-product of my investigation and attempt to fix sparklemotion/nokogiri#1175.

### CODE REVIEW

**Comment by jamis** [comment]
I'd like to offer my own humble :+1: for this pull request. I've recently run into an issue with some gems (like nokogiri, which uses mini_portile for installation) when trying to install them to a path with spaces in it. The install fails because the path components are not being escaped properly. For now, I can simply just "not do that" -- avoid having spaces in path names -- but it would be nice to have this fixed so that others don't have to spend hours troubleshooting the same problem.

**Comment by larskanis** [comment]
This pull request breaks the Windows compatibility, but I hope, that #52
can be merged.

**Comment by flavorjones** [comment]
This is superseded by @larskanis's PR #54, which I'm merging now.

Thanks to @knu who submitted the original suggested implementation, and everyone else who's waiting patiently for this.

**Comment by knu** [comment]
Thanks!

**Comment by flavorjones** [comment]
#54 has been merged. Thank you!

**Pull request closed without merging**
