### PR TITLE
Skip progress report when Content-Length is unavailable

### LINKED ISSUE #85: Unable to download files when Content-Encoding is chunked
`MiniPortile#download_file_http` relies on the Content-Length header, but it isn't sent when Content-Encoding is chunked. In this case, `content_length_proc` is called with nil.
https://github.com/flavorjones/mini_portile/blob/v2.3.0/lib/mini_portile2/mini_portile.rb#L454-L460
Although mini_portile requests with `Accept-Encoding: identity`, some servers (e.g., GitHub) respond with `Content-Encoding: chunked`

### PR DESCRIPTION
**Pull request by eagletmt**
This should fix #85

### CODE REVIEW

**Comment by Paxa** [comment]
Thanks for fixing it!

**Comment by thijsc** [comment]
Anything holding this back? Would be nice to get this out in a release, it would fix installation of the `rdkafka` gem. Probably effects a lot of other gems using the same approach too.

**Comment by flavorjones** [comment]
Sorry, nothing is holding this back except my inability to find time to work on OSS this month. Will get a release out this weekend.

**Comment by kevindew** [comment]
@flavorjones Any chance you'll get to look at this again soon?

**Comment by flavorjones** [comment]
Hey all -- apologies for the slow response. I've merged this! Will cut a release shortly.

**Comment by flavorjones** [comment]
mini_portile2 v2.4.0 has been shipped. Thanks again!

**Pull request merged**
