### PR TITLE
Create release binary with cmake explicitly

### PR DESCRIPTION
**Pull request by Watson1978**
When I built library with the default setting, its compilation has no optimized in my environment.
I want it has release binary by default.

Ref. https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html

### CODE REVIEW

**Comment by flavorjones** [comment]
@Watson1978 Thank you for submitting this pull request and updating the tests!

I'm not a CMake user, so I want to check with one other person who's contributed improvements to CMake: @stanhu what do you think of default to `Release`? Should we provide the ability to configure that setting?

**Comment by stanhu** [comment]
Default to `Release` sounds reasonable. It appears that this shrinks the re2 gem `.so` from 2766744 bytes to 1506992 bytes.

It would be nice to configure this in order to see backtraces, but I suppose that could also be done by adding `CMAKE_BUILD_TYPE` since I think the last value specified wins.

**Comment by flavorjones** [comment]
@stanhu Thanks for the fast feedback. I'm going to add a config param / env var override like mini_portile already provides for the cmake command.

**Comment by flavorjones** [comment]
@stanhu @Watson1978 would love feedback on the commit I appended

**Comment by stanhu** [comment]
Looks good to me, thanks!

**Comment by Watson1978** [comment]
@flavorjones Thank you for your improvement. Looks good to me!

**Comment by Watson1978** [comment]
thanks!!

**Comment by stanhu** [comment]
> I delayed because I was nervous about the not-fully baked pkgconfig feature on main, but will just pull the trigger.

I'll take a look in the context of https://github.com/mudge/re2/issues/109.

**Comment by flavorjones** [comment]
@stanhu Cut [Release 2.8.5 / 2023-10-22 · flavorjones/mini\_portile](https://github.com/flavorjones/mini_portile/releases/tag/v2.8.5)

**Pull request merged**
