### PR TITLE
Escape backward compat issue

### PR DESCRIPTION
**Pull request by larskanis**
So this is my proposal for the issue discussed here: https://groups.google.com/d/msg/nokogiri-talk/FLm2_U0KesU/7Y8iutkCEwAJ . It includes https://github.com/flavorjones/mini_portile/pull/59 .

We might also note about the change of the require name, by releasing a version 0.6.3 like this: https://github.com/flavorjones/mini_portile/compare/master...larskanis:v0.6.x

### CODE REVIEW

**Comment by larskanis** [comment]
@flavorjones Did you find some time to look at this?

The important part here is about the versioning. We need to make sure, that people become aware of this issue and show them how it's addressed. I hope my English is good enough, but feel free to tweak it. 

The unescape feature is probably not really needed with proper versioning, so I removed your hard work. However I don't have a strong opinion on this.

For a 0.6.3 release I could open a branch with the changes made [here](https://github.com/flavorjones/mini_portile/compare/master...larskanis:v0.6.x) . I'm not entirely sure, which base commit I should use for this branch. Do you have an opinion?

**Comment by larskanis** [comment]
I did a short install test with all nokogiri versions with the mini_portile-0.7.0.rc4 installed on Ubuntu-15.04. It works with all versions except nokogiri-1.6.2. This one installs only mini_portile-0.6.x, because of a different style of configure_options.

**Comment by flavorjones** [comment]
I'm looking into this today, apologies for the delay. It's been tough for
me to work on OSS during the week.

**Comment by flavorjones** [comment]
Hi Lars,

Thanks for giving me some time to think about this.

I agree that you're right, guessing about shell character escaping is too great of a risk for breaking backwards-compatibility somewhere in an existing dependency.

To that end, I'm happy to merge the majority of the changes from this PR, but I think I'd like take two additional steps:

1. Issue a new gem, named `mini_portile2`; and leave the gem `mini_portile` as it is.
I think it's too confusing to depend on a gem named `mini_portile`, and then remember to require `mini_portile2`. Additionally it becomes difficult to add the gem to a Gemfile, because everyone will have to remember to add `:require => 'mini_portile2'` to the gem spec.

2. When the `mini_portile2.rb` file is loaded, check for the presence of `mini_portile2` in `Gem.loaded_specs`, and emit a WARNING message if it's absent. Its absence indicates that the developer hasn't specified a Gem constraint according to your README additions and thus introduces the risk of future breakage.

Thoughts? I'm going to fork this PR and start work, but let me know if you object or have other ideas.

**Comment by larskanis** [comment]
> I agree that you're right, guessing about shell character escaping is too great of a risk for breaking backwards-compatibility somewhere in an existing dependency.

Thank you very much, I'm eased!

> 1. Issue a new gem, named `mini_portile2`; and leave the gem `mini_portile` as it is.
>I think it's too confusing to depend on a gem named `mini_portile`, and then remember to require `mini_portile2`. Additionally it becomes difficult to add the gem to a Gemfile, because everyone will have to remember to add `:require => 'mini_portile2'` to the gem spec.

I thought about this option, too. But I made a virtue out of necessity in [this commit](https://github.com/larskanis/mini_portile/commit/2016bc76f11c1a813cfee8b356d2ee99aba08458) . However both is OK for me.

> 2. When the `mini_portile2.rb` file is loaded, check for the presence of `mini_portile2` in `Gem.loaded_specs`, and emit a WARNING message if it's absent. Its absence indicates that the developer hasn't specified a Gem constraint according to your README additions and thus introduces the risk of future breakage.

I tried this, too, but it didn't work. As soon as `mini_portile2.rb` is called the previous state of `Gem.loaded_specs`is lost, because require adds the gem, before the file is executed. I couldn't find a way to test for a `gem` constraint within the mini_portile library.

**Comment by flavorjones** [comment]
Per conversation with @larskanis, going to merge the first three commits in this PR and issue this code as a new gem, `mini_portile2`. Working branch is `flavorjones-v2`

**Comment by flavorjones** [comment]
@larskanis I also just tried and failed to test for the existence of a `gem` constraint. Sigh.

@drbrain can you think of any way to know `Gem::Dependency` requirements have been declared? For context, we want to raise an exception if a constraint hasn't been placed on the `mini_portile2` version.

**Comment by larskanis** [comment]
If I read the rubygems-sources right, there is no reliable way to get this
information.

The only alternative I can think of, is to compare the gemspec-dependencies
of the gem, that is currently in installation, with the loaded version of
mini_portile. This however will not trigger a fault to the gem author, but
only later, when a newer mini_portile version was released.

So I think we can only instruct per the Readme and maybe in a 0.6.3 release.

**Pull request closed without merging**
