### PR TITLE
Add some useful outputs to debug errors

### PR DESCRIPTION
**Pull request by brayanhenao**
Add outputs to the `download_file_http` function:

- Print the URL from which the file is downloaded.
- Print the parameters of the HTTP Call.
- In the case there is an HTTP error, print the status and the body of it.

### CODE REVIEW

**Comment by flavorjones** [comment]
Thank you! I've kicked off CI and will take a closer look tomorrow.

**Comment by flavorjones** [comment]
@brayanhenao Thanks again for proposing this. After reading, my primary concern is that HTTP proxy credentials may be leaked into a log when used.

Would you be open to dropping that line from this PR? Alternatively, this might be a good time to introduce a `debug` or `verbose` option to the constructor's `**kwargs` parameter. WDYT?

**Comment by brayanhenao** [comment]
Hi, @flavorjones I'll find some time this weekend/next week to make the change!

**Comment by flavorjones** [comment]
Closing this, though I'd be open to better error messages if @brayanhenao or someone else wants to pick this up.

**Pull request closed without merging**
